<a href="https://colab.research.google.com/github/Oxygen0-0/study-2023sum/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 格點

In [6]:
import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [18]:
y = np.arange(10)  # 類似 Python 的 range, 但是回傳 array
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 基本運算

In [17]:
a = np.array([1, 2, 3, 6])
b = np.linspace(0, 2, 4)  # 建立一個array, 在0與2的範圍之間讓4個點3等分
c = a - b
c

array([1.        , 1.33333333, 1.66666667, 4.        ])

In [9]:
a**2

array([ 1,  4,  9, 36])

# 全域方法

In [10]:
a = np.linspace(-np.pi, np.pi, 100)
b = np.sin(a)
c = np.cos(a)

# 線性代數

In [11]:
from numpy.random import rand
from numpy.linalg import solve, inv
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
a.transpose()

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])

In [12]:
inv(a)

array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])

In [13]:
b =  np.array([3, 2, 1])

In [14]:
solve(a, b)  # 解方程式 ax = b

array([-4.83050847,  2.13559322,  1.18644068])

In [15]:
c = rand(3, 3)  # 建立一個 3x3 隨機矩陣
c

array([[0.14946652, 0.80622262, 0.84845202],
       [0.30590344, 0.86146409, 0.60870158],
       [0.50541662, 0.29224007, 0.90617163]])

In [16]:
np.dot(a, c)  # 矩陣相乘

array([[ 2.27752327,  3.40587103,  4.78437005],
       [ 5.0583047 ,  7.82253274, 11.05151226],
       [ 6.02754668, 13.24549032, 14.25143242]])